plugins: rubocop-capybara

Capybara/AmbiguousClick:
  Enabled: true
Capybara/FindAllFirst:
  Enabled: true
Capybara/AssertStyle:
  Enabled: true
Capybara/RedundantWithinFind:
  Enabled: true
Capybara/RSpec/HaveSelector:
  Enabled: true
Capybara/RSpec/MatchStyle:
  Enabled: true
Capybara/RSpec/NegationMatcher:
  Enabled: true
Capybara/RSpec/NegationMatcherAfterVisit:
  Enabled: true
Capybara/RSpec/PredicateMatcher:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/RSpec/SpecificMatcher:
  Enabled: true
