plugins: rubocop-capybara

Capybara/ClickLinkOrButtonStyle:
  Enabled: true
Capybara/FindAllFirst:
  Enabled: true
Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/NegationMatcherAfterVisit:
  Enabled: true
Capybara/RedundantWithinFind:
  Enabled: true
Capybara/RSpec/HaveSelector:
  Enabled: true
Capybara/RSpec/PredicateMatcher:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
