require: rubocop-factory_bot

FactoryBot/AssociationStyle:
  Enabled: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
  EnforcedStyle: omit_parentheses
FactoryBot/ExcessiveCreateList:
  Enabled: true
  MaxAmount: 5
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/IdSequence:
  Enabled: true
FactoryBot/RedundantFactoryOption:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: false
