require: rubocop-factory_bot

FactoryBot/AssociationStyle:
  Enabled: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
  EnforcedStyle: omit_parentheses
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: false
