plugins: rubocop-performance

Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConcurrentMonotonicTime:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/IoReadlines:
  Enabled: true
Performance/MapCompact:
  Enabled: true
Performance/MapMethodChain:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/OpenStruct:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/StringIdentifierArgument:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringBytesize:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true
Performance/ZipWithoutBlock:
  Enabled: true
