require: rubocop-rspec

RSpec/BeEmpty:
  Enabled: true
RSpec/BeEq:
  Enabled: true
RSpec/BeNil:
  Enabled: true
  EnforcedStyle: be
RSpec/ChangeByZero:
  Enabled: true
RSpec/ClassCheck:
  Enabled: true
RSpec/ContainExactly:
  Enabled: true
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - feature
      - request
      - task
RSpec/DescribedClassModuleWrapping:
  Enabled: true
RSpec/Dialect:
  Enabled: true
  PreferredMethods:
    append_after: after
    append_before: before
    example: it
    example_group: context
    expect_any_instance_of: expect
    is_expected: expect
    its: it
    let!: let
    prepend_after: after
    prepend_before: before
    shared_examples_for: shared_examples
    specify: it
    subject!: subject
RSpec/DuplicatedMetadata:
  Enabled: true
RSpec/EmptyMetadata:
  Enabled: true
RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
RSpec/ExcessiveDocstringSpacing:
  Enabled: true
RSpec/Eq:
  Enabled: true
RSpec/FilePath:
  Enabled: false
RSpec/IdenticalEqualityAssertion:
  Enabled: true
RSpec/IndexedLet:
  Enabled: true
RSpec/IsExpectedSpecify:
  Enabled: true
RSpec/MatchArray:
  Enabled: true
RSpec/MetadataStyle:
  Enabled: true
RSpec/NamedSubject:
  IgnoreSharedExamples: false
RSpec/NoExpectationExample:
  Enabled: true
RSpec/PendingWithoutReason:
  Enabled: true
RSpec/ReceiveMessages:
  Enabled: true
RSpec/RedundantAround:
  Enabled: true
RSpec/RedundantPredicateMatcher:
  Enabled: true
RSpec/RemoveConst:
  Enabled: true
RSpec/RepeatedSubjectCall:
  Enabled: true
RSpec/Rails/AvoidSetupHook:
  Enabled: true
RSpec/Rails/HaveHttpStatus:
  Enabled: true
RSpec/Rails/InferredSpecType:
  Enabled: true
RSpec/Rails/MinitestAssertions:
  Enabled: true
RSpec/Rails/NegationBeValid:
  Enabled: true
  EnforcedStyle: be_invalid
RSpec/Rails/TravelAround:
  Enabled: true
RSpec/SkipBlockInsideExample:
  Enabled: true
RSpec/SortMetadata:
  Enabled: true
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true
RSpec/SubjectDeclaration:
  Enabled: true
RSpec/VerifiedDoubleReference:
  Enabled: true
