require: rubocop-rspec

RSpec/BeEmpty:
  Enabled: true
RSpec/BeEq:
  Enabled: true
RSpec/BeNil:
  Enabled: true
  EnforcedStyle: be
RSpec/ChangeByZero:
  Enabled: true
RSpec/ClassCheck:
  Enabled: true
RSpec/ContainExactly:
  Enabled: true
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - feature
      - request
      - task
RSpec/DescribedClassModuleWrapping:
  Enabled: true
RSpec/Dialect:
  Enabled: true
  PreferredMethods:
    append_after: after
    append_before: before
    example: it
    example_group: context
    expect_any_instance_of: expect
    is_expected: expect
    its: it
    let!: let
    prepend_after: after
    prepend_before: before
    shared_examples_for: shared_examples
    specify: it
    subject!: subject
RSpec/DuplicatedMetadata:
  Enabled: true
RSpec/ExampleLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
RSpec/ExcessiveDocstringSpacing:
  Enabled: true
RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
  EnforcedStyle: omit_parentheses
RSpec/FactoryBot/FactoryNameStyle:
  Enabled: true
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false
RSpec/IdenticalEqualityAssertion:
  Enabled: true
RSpec/IndexedLet:
  Enabled: true
RSpec/MatchArray:
  Enabled: true
RSpec/NamedSubject:
  IgnoreSharedExamples: false
RSpec/NoExpectationExample:
  Enabled: true
RSpec/PendingWithoutReason:
  Enabled: true
RSpec/RedundantAround:
  Enabled: true
RSpec/Rails/AvoidSetupHook:
  Enabled: true
RSpec/Rails/HaveHttpStatus:
  Enabled: true
RSpec/Rails/InferredSpecType:
  Enabled: true
RSpec/Rails/MinitestAssertions:
  Enabled: true
RSpec/Rails/TravelAround:
  Enabled: true
RSpec/SkipBlockInsideExample:
  Enabled: true
RSpec/SortMetadata:
  Enabled: true
RSpec/SubjectDeclaration:
  Enabled: true
RSpec/VerifiedDoubleReference:
  Enabled: true
