plugins: rubocop-thread_safety

ThreadSafety/ActiveSupportCallbacks:
  Enabled: true
ThreadSafety/ClassInstanceVariable:
  Enabled: false
ThreadSafety/DirChdir:
  Exclude:
    - "bin/setup"
ThreadSafety/MethodRedefinition:
  Enabled: true
