plugins: rubocop-thread_safety

ThreadSafety/ActiveSupportCallbacks:
  Enabled: true
ThreadSafety/ClassInstanceVariable:
  Enabled: false
ThreadSafety/DirChdir:
  Exclude:
    - "bin/setup"
ThreadSafety/EnvMutation:
  Enabled: true
  Exclude:
    - "spec/**/*"
ThreadSafety/LazySynchronizationPrimitive:
  Enabled: true
ThreadSafety/MethodRedefinition:
  Enabled: true
